# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - llano-velasco-prueba

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    # Cancelar  aa
    - name: Cancel Previous Runs
      uses: styfle/cancel-workflow-action@0.8.0

    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: TEST
      run: |
        cd vista
        npm install
        npm install chrome
        npm test

    - name: Login Docker Huub
      uses: docker/login-action@v2
      with: 
        username: ${{secrets.DOCKERHUB_USERNAME}}
        password: ${{secrets.DOCKERHUB_TOKEN}}

    - uses: actions/checkout@v3
    - uses: isbang/compose-action@v1.4.1
      with:
        compose-file: docker-compose.yml
        down-flags: "--volumes"
        push: true
        build: true
        services: |
          spring
          angular
        run: |
          npm test
    - run: 'docker-compose push'  
